# /wordpress-docker/docker-compose.yml
---
services:
  db:
    container_name: 'localwordpress-db'
    image: 'mysql:8.0'
    volumes:
      - './data/mysql:/var/lib/mysql'
    ports:
      - 18766:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin1
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin101
  wordpress:
    container_name: 'localwordpress'
    depends_on:
      - db
    image: 'wordpress:latest'
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: 'db:3306'
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: admin101
      WORDPRESS_DB_NAME: wordpressdb
    volumes:
      - "./wordpress:/var/www/html"
      - "./plugins:/var/www/html/wp-content/plugins"